title: "Bruno Croci's Art"
description: "photography, digital art, music and drawings"
author: "Bruno Croci"
url: "https://bruno.croci.art/"

images_max_height: 1024
images_quality: 65
thumbs_max_width: 512
thumbs_quality: 60

gallery_columns_desktop: 4
gallery_columns_mobile: 2
gallery_breakpoint: 1200

images_border: 70
thumbs_border: 0

sections:
  - title: "About"
    pages:
      - "index.md"
  - title: "Art Projects"
    pages:
      - "xavega/index.md"
  - title: "Gallery"
    pages:
      - "photography/index.md"

