title: "Bruno Croci's Photos"
description: "some of my photography"
author: "Bruno Croci"
url: "http://alpharaymond.crocidb.com:8080"

images_max_height: 1024
images_quality: 65
thumbs_max_width: 512
thumbs_quality: 60

images_border: 70
thumbs_border: 0

pages:
  - index.md
  - bw/index.md
