title: "Bruno Croci's Photos"
description: "some of my photography"
author: "Bruno Croci"

images_max_height: 1024
images_quality: 65
thumbs_max_height: 256
thumbs_quality: 30

images_border: 150
thumbs_border: 0

pages:
  - index.md
  - night/night.md
  - forest/forest.md
