title: "Bruno Croci's Art"
description: "photography, digital art, music and drawings"
author: "Bruno Croci"
url: "http://localhost:8081"

images_max_height: 1024
images_quality: 65
thumbs_max_width: 512
thumbs_quality: 60

images_border: 70
thumbs_border: 0

sections:
  - title: "About"
    pages:
      - "index.md"
  - title: "Art Projects"
    pages:
      - "xavega/index.md"
  - title: "Gallery"
    pages:
      - "photography/index.md"

